const RESPONSE_STATUS = {
  SUCCESS: 200,
  ERROR: 400,
  SYSTEM_ERROR: 500,
  MONGODB_DATA_NOT_FOUND: 600,
  MONGODB_DUPLICATE_INPUT: 601,
  MONGODB_VALIDATION_ERROR: 602
}

module.exports = RESPONSE_STATUS
